server:
  servlet:
    context-path: /xkRotaract

app:
  baseUrl: "http://localhost:8000/xkRotaract"

spring:
  profiles:
    active: sit
#    active: dev
#    active: uat
#    active: prod
  application:
    name: xkRotaract
  thymeleaf:
    cache: false #开发阶段，建议关闭thymeleaf的缓存
    mode: HTML5 #使用遗留的html5以去掉对html标签的校验
    check-template: true
    servlet.content-type: text/html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  resources:
    #用于告诉Spring Boot应该在何处查找静态资源文件,查找文件时会依赖于配置的先后顺序依次进行
    static-locations: classpath:/static/,classpath:/view/,classpath:/public,classpath:/resources,classpath:/META-INF/resources

# mybatis配置
mybatis:
  #    mapper-locations: classpath*:**/mapper/xml/**Mapper.xml    # mapper映射文件位置
  #    type-aliases-package: com.xk.**.model    # 实体类所在的位置
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-acmel-case: true    #開啟mybatis駝峰式命名規則自動轉換
#  mybatis-plus:
#    mapper-locations: classpath*:**/mapper/xml/**Mapper.xml    # mapper映射文件位置

