server:
  port: 8000
  error:
    whitelabel:
      enabled: false  # 禁用默认的白标签错误页面

app:
  baseUrl: "http://localhost:8000/xkRotaract"

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver # 驅動類型(注意MySQL 8.0的值是com.mysql.cj.jdbc.Driver和之前不同)
    url: jdbc:mysql://localhost:3306/rotaract?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8 # 數據庫連接字符串
    username: root # 數據庫用戶名
    password: 1qaz@WSX # 數據庫密碼
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true # 默认false，在日志里显示执行的sql语句
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
      ddl-auto: update #none:nothing, update:update new, create:rebootDB
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
    #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true

# ===== 自定義 swagger 配置 ===== #
springfox:
  documentation:
    swagger-ui:
      enabled : true

#  OFF：关闭所有日志记录。
#  FATAL：仅记录严重的错误，可能导致应用程序崩溃的情况。
#  ERROR：记录错误信息，表示应用程序在运行中出现了问题。
#  WARN：记录潜在的问题或警告，但不一定是错误。
#  INFO：记录常规信息，通常用来了解应用程序的状态或进程。
#  DEBUG：记录详细的调试信息，用于开发和调试阶段，包含应用程序的内部状态、变量值等。
#  TRACE：记录最详细的日志信息，包括每一步的执行情况，比DEBUG更详细。
#  ALL：打开所有级别的日志记录（从TRACE到FATAL）。
logging:
  level:
    root: INFO         # 全局日志级别设置为 INFO
    org.springframework: INFO  # 启用 Spring 的调试日志
    org.thymeleaf: INFO  # 启用 Thymeleaf 的调试日志
    com.xk: INFO      # 仅为 com.xk 包启用 DEBUG 级别日志
  file:
    path: ./logs       # 指定日志文件的路径（请确保路径存在）
    name: log-pro.log  # 指定日志文件的名称
  console:
    level: INFO       # 控制台日志级别设置为 DEBUG



